[RunSvc]
JobName = "srunet3d_6x6x8_128x128x128_beam0"
BeamType = "IAEA"
# PhspInputFileName = "/mnt/data/PHSP/TB_20X20_Merged"
# PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH Dell-XPS location
# PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_3x3s2-f0" # AGH LHCBD2 location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location 

PhspEvtVrtxMultiplicityTreshold = 20
PrintProgressFrequency = 0.05
Physics = "LowE_Penelope" #  "LowE_Livermore" "LowE_Penelope" "emstandard_opt3"

GenerateCT = true
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

WriteFieldMaskToCsv = true

StoreTracks= false
StorePositions= false
StoreEnergies = false
StorePrimaries = false
StoreRunInfo= false
MinimalMode= true

[GeoSvc]
BuildLinac = true
BuildPatient = true
MlcModel="Simplified"

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 0.0
EnviromentSizeX = 128.0
EnviromentSizeY = 128.0
EnviromentSizeZ = 128.0
EnviromentMedium = "Usr_G4AIR20C"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,-80.0] # In mm
Voxelization = [6,6,8] # Number of cels in every direction

[D3DDetector_Cell]
Medium = "RMPS470"
Voxelization = [10,10,10]
TracksAnalysis = false
CellVoxelisedScorer = true

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
# nParticles = 10000
PlanInputFile = [
        "plan/custom/prostate/prostate_imrt_beam0_cp0.dat"
]