[RunSvc]
JobName = "angle_study"
BeamType = "IAEA" # "gps" IAEA 
# BeamType = "gps" # "gps" IAEA 
PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
PhspInputPosition = "s2"
# GpsMacFileName = "/home/g4rt/test/g4rt/scripts/gps/gpsCLiniac_but_parallel.mac"
PrintProgressFrequency = 0.005
NTupleAnalysis = true 
# FieldShape = "Rectangular" # "Elipsoidal", "RTPlan"
FieldShape = "Elipsoidal" 
FieldSizeA = 40 # mm
FieldSizeB = 40 # mm

[PatientGeometry]
# Type = "D3DDetector"
Type = "WaterPhantom"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 120.0
EnviromentSizeY = 120.0
EnviromentSizeZ = 120.0
EnviromentMedium = "G4_WATER"



[WaterPhantom_Detector]
TranslationFromCentre = [0.0,0.0,0.0] # In mm
Voxelization = [2,2,2] # Number of cels in every direction
Size = [100.0,100.0,100.0]
Medium = "G4_WATER" #G4_WATER, PMMA

[WaterPhantom_Scoring]
FullVolume = true
FarmerDoseCalibration = false
TracksAnalysis = true


[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 2
Gantry_Angle_Per_Control_Point = [0.0,90.0]
Particle_Counter_Per_Control_Point = [2e5,2e5]

[LogSvc_D3DCell]
LogLevel = "debug"
