[RunSvc]
JobName = "tld_basic_30_deg"
BeamType = "gps"
GpsMacFileName = "gps/gps_x_ray_tube_20_kev_molybdenum.mac"
Physics = "LowE_Penelope" 
PhspEvtVrtxMultiplicityTreshold = 10
PrintProgressFrequency = 0.01
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true
EnableExtraProcesses = true

StoreTracks= false
StorePositions= false
StoreEnergies = false
StorePrimaries = false
StoreRunInfo= false
MinimalMode= true


[GeoSvc]
BuildLinac = true
BuildPatient = false
ExportGeometryToGDML = true
MlcModel = "Simplified"

[TLDTray]
Position = [0.0,0.0,0.0] 
Rotation = [0.0,0.0,0.0]
World_Size = [150.0,150.0,150.0]
TLDGrid = [4,4] # X, Y
TLDVoxelization = [37,37,11]
TLDMedium = "LiF:Mg,Ti"
# TLDMedium = "G4_Fe"
TLD_Geometry_File_Path = "tldGeometry/standard.stl"

SupplementaryGeometry = "/home/jackie/Dokumenty/work/development/TLD/d3df_g4rt/data/tldGeometry/holder.stl"
SupplementaryGeometryMaterial = "PMMA"
SupplementaryGeometryPosition = [0.0, 0.0, -2.05]
SurfaceScoringLayers = 3

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
nParticles = 5000000
BeamRotation = 30.0 # in degrees, rotation of the beam around the Z axis (in the XY plane)
BeamSID = 100.0 # (Obecne pole naświetlania koło o średnicy 16 cm (x od -8 cm do +8 cm/ y od -8 cm do +8 cm)
PlanInputFile = [
    "plan/custom/cp10x10.dat"
]
