[RunSvc]
JobName = "tld_basic"
BeamType = "gps"
GpsMacFileName = "gps/gps_x_ray_tube_70_kev.mac" # BR AGH pc location
PhspEvtVrtxMultiplicityTreshold = 10
PrintProgressFrequency = 0.05
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = false
ExportGeometryToGDML = true
MlcModel = "Simplified"

[TLDTray]
Position = [0.0,0.0,0.0] 
Rotation = [0.0,0.0,0.0]
TLDVoxelization = [20,20,10]
TLDMedium = "LiF:Mg,Ti"
TLD_Geometry_File_Path = "tldGeometry/three-hole.stl"

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
nParticles = 1000
BeamRotation = 90.0
PlanInputFile = [
    "plan/custom/cp10x10.dat"
]
