[RunSvc]
JobName = "NIO_Tower_2023-12-16"
BeamType = "IAEA"
PhspInputFileName = "/etude/jhajduga/data/mc/PHSP/TNSIM157_10x10s2-f0"
PhspEvtVrtxMultiplicityTreshold = 55
PrintProgressFrequency = 0.001
Physics = "LowE_Penelope" #  "LowE_Livermore" "LowE_Penelope" "emstandard_opt3"
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true
EnableExtraProcesses = true

StoreTracks= false
StorePositions= false
StoreEnergies = false
StorePrimaries = false
StoreRunInfo= false
MinimalMode= true

[GeoSvc]
BuildLinac = true
BuildPatient = true
MlcModel="Simplified"


[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX       = 0.0
PatientIsocentreY       = 0.0
PatientIsocentreZ       = 197.5
EnviromentSizeX         = 680.0
EnviromentSizeY         = 710.0
EnviromentSizeZ         = 460.0
EnviromentMedium = "Usr_G4AIR20C"
EnviromentPatientEnvelop = "ModularWaterPhantom_3mf" # 
PatientDBPath = "d3df-patients/patient/phantoms/NIO_Tower_2023-12-16" 

[GeometryBuilder]
ExcludeObjList = []
Position = [0.0, 0.0, 0.0] # Position X/Y/Z inside the patient environment
Rotation = [0.0, 0.0, 0.0] # Rotation aouynd axis X/Y/Z inside the patient environment

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [5,5,5]


[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
nControlPoints = 1      # This will limit number of ctrl points defined below!
BeamRotation = 0        # This will overwrite Rotation value for all below plan files!
nParticles = 1e4     # This will overwrite Rotation value for all below plan files!
PlanInputFile = [
        "plan/custom/cp4_1x4_1.dat"
]