[RunSvc]
JobName = "CT Test"
BeamType = "IAEA" 
# PhspInputFileName = "/mnt/c/Users/Jakub/Desktop/phsp/Cliniac2100s2-f0" # AGH JH File
PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
# GpsMacFileName = "gps/gpsCLinac.mac"
PrintProgressFrequency = 0.01
Physics = "LowE_Penelope"
NTupleAnalysis = true 
PrimariesAnalysis = true
# FieldShape = "Rectangular"
FieldShape = "Elipsoidal"
FieldSizeA = 20 # mm
FieldSizeB = 20 # mm

[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 300.0
EnviromentSizeY = 300.0
EnviromentSizeZ = 300.0
EnviromentMedium = "G4_WATER"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,0.0,-140.0] # In mm
Geomertry = "CT_positioner/direction_cube.stl"

[D3DDetector_Layer]
Positioning = "CT_positioner/positioning.csv"

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [2,2,2]

# [D3DDetector_Detector]
# TopPositionInEnv = [0.0,0.0,-199.0] # In mm
# Voxelization = [4,4,4] # Number of cels in every direction

# [D3DDetector_Layer]
# MRowShift = false
# MLayerShift = false

# [D3DDetector_Cell]
# Medium = "PMMA" #G4_WATER, PMMA
# Voxelization = [4,4,4]
# TracksAnalysis = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0]
Particle_Counter_Per_Control_Point = [1e3]

[LogSvc_D3DCell]
LogLevel = "debug"