[RunSvc]
JobName = "tracks_ana_test"
BeamType = "IAEA" # "gps" IAEA 
# BeamType = "gps" # "gps" IAEA 
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/BestPHSPs1_10e8hist" # AGH JH File
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location

PrintProgressFrequency = 0.001
NTupleAnalysis = true 
FieldSize = 400 # mm


[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 30.0
EnviromentSizeY = 30.0
EnviromentSizeZ = 30.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,0.0,-15.0] # In mm
Voxelization = [2,2,2] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [2,2,2]
TracksAnalysis = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0]
Particle_Counter_Per_Control_Point = [1e5]

[LogSvc_D3DCell]
LogLevel = "debug"
