[RunSvc]
JobName = "Testing gps in new ntuple format"
BeamType = "gps" 
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
GpsMacFileName = "gps/gpsCLinac.mac"
PrintProgressFrequency = 0.05
NTupleAnalysis = true 
# FieldShape = "Rectangular"
FieldShape = "Elipsoidal"
FieldSizeA = 30 # mm
FieldSizeB = 30 # mm

[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 50.0
EnviromentSizeY = 50.0
EnviromentSizeZ = 80.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,0.0,-20.0] # In mm
Voxelization = [4,4,5] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [5,5,5]
TracksAnalysis = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0]
Particle_Counter_Per_Control_Point = [5e3]

[LogSvc_D3DCell]
LogLevel = "debug"