[RunSvc]
JobName = "gps_RMPS_emstandard_upgrade"
BeamType = "gps"
PhspInputFileName = "/mnt/c/PRIMO/phsptest/phsptests2-f0" # AGH JH File
GpsMacFileName = "/home/g4rt/test/diff_size/g4rt/data/gps/CLinac_pararell.mac"
PrintProgressFrequency = 0.01
NTupleAnalysis = true
# Physics = "LowE_Penelope" #"LowE_Penelope"
# FieldShape = "Rectangular" # "Elipsoidal", "RTPlan"
FieldShape = "Elipsoidal"
FieldSizeA = 25 # mm
FieldSizeB = 25 # mm

[GeoSvc]
BuildLinac = false
BuildPatient = true

[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 60.5
EnviromentSizeX = 35.0
EnviromentSizeY = 35.0
EnviromentSizeZ = 120.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,0.0,-60.0] # In mm
Voxelization = [1,1,10] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470"
Voxelization = [2,2,2]
TracksAnalysis = true
WriteCellTTree = true
WriteVoxelisedCellTTree = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0,30.0]
Particle_Counter_Per_Control_Point = [2e6,2e6]
