[RunSvc]
JobName = "d3df example job"
BeamType = "IAEA"
PhspInputFileName = "/mnt/data/PHSP/TB_20X20_Merged"

PhspEvtVrtxMultiplicityTreshold = 20
PrintProgressFrequency = 0.05
Physics = "LowE_Penelope" #  "LowE_Livermore" "LowE_Penelope" "emstandard_opt3"

GenerateCT = true

PrimariesAnalysis = false
NTupleAnalysis = false
RunAnalysis = true


[GeoSvc]
BuildLinac = true
BuildPatient = true
MlcModel="Simplified"

[PatientGeometry]
Type = "GenericPhantom"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 0.0

EnviromentSizeX = 1400.0
EnviromentSizeY = 1400.0
EnviromentSizeZ = 1400.0


VoxelSizeXCT = 7.0
VoxelSizeYCT = 7.0
VoxelSizeZCT = 7.0


EnviromentMedium = "Usr_G4AIR20C"
EnviromentPatientEnvelop = "GenericPhantom_3mf"
PatientDBPath = "d3df-patients/patient/phantoms/modular_water_phantom" 
ConfigPrefix = "GenericPhantom"

[GenericPhantom]
Position = [0.0, 0.0, 0.0]
Rotation = [0.0, 0.0, 0.0]
ExcludeObjList = []

[RunSvc_Plan]
nParticles = 500
PlanInputFile = [
        "plan/custom/cp10x10.dat"
]