[RunSvc]
JobName = "web_job_example"
BeamType = "IAEA" # "gps" IAEA 
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/BestPHSPs1_10e8hist" # AGH JH File
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # 121 JH workstation file location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
# PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # BR AGH laptop location
# PhspInputFileName = "/mnt/e/dose3d/TNSIM157_3x3s2-f0" # MN location
# PhspInputFileName = "/home/madej/testmnt/TNSIM157_3x3s2-f0" # PM AGH laptop location

PrintProgressFrequency = 0.01
NTupleAnalysis = true 
# FieldShape = "Rectangular"
FieldShape = "Elipsoidal"
FieldSizeA = 10 # mm
FieldSizeB = 30 # mm

[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 50.0
EnviromentSizeY = 50.0
EnviromentSizeZ = 80.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,0.0,-20.0] # In mm
Voxelization = [3,2,5] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [5,5,5]
TracksAnalysis = false
WriteCellTTree = false
WriteVoxelisedCellTTree = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 2
Gantry_Angle_Per_Control_Point = [0.0,45.0,75.0]
Particle_Counter_Per_Control_Point = [1e4,1e4,1e5]

[LogSvc_D3DCell]
LogLevel = "debug"
